"""init

Revision ID: f7834a03c8e6
Revises: 
Create Date: 2026-09-12 18:45:16.106773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7834a03c8e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('full_name', sa.String(length=256), nullable=False),
    sa.Column('ref_code', sa.String(length=16), nullable=False),
    sa.Column('referrer_id', sa.BigInteger(), nullable=True),
    sa.Column('active_order_id', sa.Integer(), nullable=True),
    sa.Column('support_thread_id', sa.Integer(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref_code')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_referrer_id'), ['referrer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_support_thread_id'), ['support_thread_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('work_type', sa.String(length=32), nullable=False),
    sa.Column('topic', sa.String(length=256), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('estimate_min', sa.Integer(), nullable=True),
    sa.Column('estimate_max', sa.Integer(), nullable=True),
    sa.Column('base_price', sa.Integer(), nullable=True),
    sa.Column('discount_percent', sa.Integer(), nullable=False),
    sa.Column('final_price', sa.Integer(), nullable=True),
    sa.Column('prepay_percent', sa.Integer(), nullable=True),
    sa.Column('prepay_amount', sa.Integer(), nullable=True),
    sa.Column('paid_amount', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=True),
    sa.Column('card_message_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_thread_id'), ['thread_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_user_id'), ['user_id'], unique=False)

    op.create_table('order_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(length=256), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_files_order_id'), ['order_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('receipt_file_id', sa.String(length=256), nullable=False),
    sa.Column('receipt_is_photo', sa.Boolean(), nullable=False),
    sa.Column('admin_message_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_order_id'), ['order_id'], unique=False)

    op.create_table('price_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('base_price', sa.Integer(), nullable=False),
    sa.Column('discount_percent', sa.Integer(), nullable=False),
    sa.Column('final_price', sa.Integer(), nullable=False),
    sa.Column('prepay_percent', sa.Integer(), nullable=False),
    sa.Column('prepay_amount', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('client_message_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_offers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_offers_order_id'), ['order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_offers_order_id'))

    op.drop_table('price_offers')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_order_id'))

    op.drop_table('payments')
    with op.batch_alter_table('order_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_files_order_id'))

    op.drop_table('order_files')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_user_id'))
        batch_op.drop_index(batch_op.f('ix_orders_thread_id'))
        batch_op.drop_index(batch_op.f('ix_orders_status'))

    op.drop_table('orders')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_support_thread_id'))
        batch_op.drop_index(batch_op.f('ix_users_referrer_id'))

    op.drop_table('users')
    # ### end Alembic commands ###
